# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CW1YIQK_08hLngjb3DCaxCP7aGtHuSaW
"""

import streamlit as st
import pickle
import re

# Load model and vectorizer
model = pickle.load(open("fake_news_model.pkl", "rb"))
tfidf = pickle.load(open("tfidf_vectorizer.pkl", "rb"))

# Text cleaning function (same as training)
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text

# Streamlit UI
st.set_page_config(page_title="Fake News Detection", page_icon="📰")

st.title("📰 Fake News Detection System")
st.write("Paste a news article below to check whether it is **Fake** or **Real**.")

user_input = st.text_area("Enter news text here:")

if st.button("Check News"):
    if user_input.strip() == "":
        st.warning("Please enter some news text.")
    else:
        cleaned_text = clean_text(user_input)
        vectorized_text = tfidf.transform([cleaned_text])
        prediction = model.predict(vectorized_text)[0]

        if prediction == 1:
            st.success("✅ This is REAL news")
        else:
            st.error("❌ This is FAKE news")